version : '3'
services :
  user-profile:
    image: djerror327/nana-app:1.0
    ports: 
    - 3000:3000
    container_name: nana-user-profile
    restart: always
  mongodb:
    image: mongo
    container_name: mongo-db
    restart: always
    ports: 
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    restart: always
    ports: 
    - 8080:8081
    environment: 
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
     - ME_CONFIG_MONGODB_SERVER=mongo-db